language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk: oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
install: true
addons:
  postgresql: "9.6"
  apt:
    packages:
      - oracle-java8-installer
script:
  - jdk_switcher use oraclejdk8
  - mvn clean verify -B -Ddb_user=travis -Ddb_password -Dit_db_name=travis -P!createdb
services:
  - postgresql
before_script:
  - sleep 10