dist: trusty
sudo: true
language: java
jdk: oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sudo sysctl -w vm.max_map_count=262144
script:
  - travis_wait 30 mvn verify -B -Ddb_user=travis -Ddb_password -Dit_db_name=travis -P!createdb