language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk: oraclejdk8
cache:
  directories:
    - node_modules
    - $HOME/.m2
install: true
script:
  - jdk_switcher use oraclejdk8
  - mvn clean test -B -DargLine="-Ddb_uri=jdbc:postgresql://localhost/travis?reWriteBatchedInserts=true&autosave=CONSERVATIVE -Ddb_user=travis -Ddb_password="
services:
  - postgresql
before_script:
  - sleep 10